import 'package:exam_5/models/experts.dart';

class Lists {
  final List<People> elements = [
    People(
        image: "assets/people/img1.jpg",
        name: "Mark Jonson",
        profession: "Cleaner",
        rating: 4.5,
        jobs: 137,
        rate: "\$12/hr"),
    People(
        image: "assets/people/img2.jpg",
        profession: "Cleaner",
        name: "Liya James",
        rating: 4.3,
        jobs: 127,
        rate: "\$10/hr"),
    People(
        image: "assets/people/img3.jpg",
        name: "Johan Watson",
        profession: "Cleaner",
        rating: 4.0,
        jobs: 117,
        rate: "\$8/hr"),
    People(
        image: "assets/people/img4.jpg",
        name: "Licha James",
        profession: "Cleaner",
        rating: 4.9,
        jobs: 140,
        rate: "\$15/hr"),
    People(
        image: "assets/people/img1.jpg",
        name: "Mark Jonson",
        rating: 4.5,
        jobs: 137,
        profession: "Cleaner",
        rate: "\$12/hr"),
    People(
        image: "assets/people/img2.jpg",
        name: "Liya James",
        rating: 4.3,
        profession: "Cleaner",
        jobs: 127,
        rate: "\$10/hr"),
    People(
        image: "assets/people/img3.jpg",
        name: "Johan Watson",
        rating: 4.0,
        profession: "Cleaner",
        jobs: 117,
        rate: "\$8/hr"),
    People(
        image: "assets/people/img4.jpg",
        name: "Licha James",
        rating: 4.9,
        profession: "Cleaner",
        jobs: 140,
        rate: "\$15/hr"),
    People(
        image: "assets/people/img1.jpg",
        name: "Mark Jonson",
        rating: 4.5,
        jobs: 137,
        profession: "Cleaner",
        rate: "\$12/hr"),
    People(
        image: "assets/people/img2.jpg",
        name: "Liya James",
        rating: 4.3,
        jobs: 127,
        profession: "Cleaner",
        rate: "\$10/hr"),
    People(
        image: "assets/people/img3.jpg",
        name: "Johan Watson",
        profession: "Cleaner",
        rating: 4.0,
        jobs: 117,
        rate: "\$8/hr"),
    People(
        image: "assets/people/img4.jpg",
        name: "Licha James",
        profession: "Cleaner",
        rating: 4.9,
        jobs: 140,
        rate: "\$15/hr"),
    People(
        image: "assets/people/img1.jpg",
        name: "Mark Jonson",
        profession: "Cleaner",
        rating: 4.5,
        jobs: 137,
        rate: "\$12/hr"),
    People(
        image: "assets/people/img2.jpg",
        profession: "Cleaner",
        name: "Liya James",
        rating: 4.3,
        jobs: 127,
        rate: "\$10/hr"),
    People(
        image: "assets/people/img3.jpg",
        name: "Johan Watson",
        profession: "Cleaner",
        rating: 4.0,
        jobs: 117,
        rate: "\$8/hr"),
    People(
        image: "assets/people/img4.jpg",
        name: "Licha James",
        profession: "Cleaner",
        rating: 4.9,
        jobs: 140,
        rate: "\$15/hr"),
    People(
        image: "assets/people/img1.jpg",
        name: "Mark Jonson",
        rating: 4.5,
        jobs: 137,
        profession: "Cleaner",
        rate: "\$12/hr"),
    People(
        image: "assets/people/img2.jpg",
        name: "Liya James",
        rating: 4.3,
        profession: "Cleaner",
        jobs: 127,
        rate: "\$10/hr"),
    People(
        image: "assets/people/img3.jpg",
        name: "Johan Watson",
        rating: 4.0,
        profession: "Cleaner",
        jobs: 117,
        rate: "\$8/hr"),
    People(
        image: "assets/people/img4.jpg",
        name: "Licha James",
        rating: 4.9,
        profession: "Cleaner",
        jobs: 140,
        rate: "\$15/hr"),
    People(
        image: "assets/people/img1.jpg",
        name: "Mark Jonson",
        rating: 4.5,
        jobs: 137,
        profession: "Cleaner",
        rate: "\$12/hr"),
    People(
        image: "assets/people/img2.jpg",
        name: "Liya James",
        rating: 4.3,
        jobs: 127,
        profession: "Cleaner",
        rate: "\$10/hr"),
    People(
        image: "assets/people/img3.jpg",
        name: "Johan Watson",
        profession: "Cleaner",
        rating: 4.0,
        jobs: 117,
        rate: "\$8/hr"),
    People(
        image: "assets/people/img4.jpg",
        name: "Licha James",
        profession: "Cleaner",
        rating: 4.9,
        jobs: 140,
        rate: "\$15/hr"),
  ];
}
